### ISSUE TITLE
Rename repository to "fontobene-converters"

### ISSUE THREAD

**Issue by ubruhin** [fontobene/fontobene-converters#1]
When cloning this repository, the organization name is no longer visible (locally). So IMHO we should prefix its name with "fontobene-".

**Comment by dbrgn** [comment]
I'm -1 on this. When working with multiple repos of an organization, I usually create a top level directory called `fontobene` and in there clone all repositories that are relevant to me.

Also on Github the namespacing is clearly visible.

When cloning this repo into a non-namespaced directory, solving this issue is as simple as `git clone https://github.com/fontobene/converters/ fontobene-converters`.

But let's see what @rnestler thinks about this :)

**Comment by ubruhin** [comment]
Of course you can specify the target directory when cloning, and on github the organization is often visible. But for example when forking a repository (and keeping the original repository name), the original organization is no longer contained in the repository path, e.g. https://github.com/ubruhin/converters, which is completely meaningless.

I (any many other people) always create such a prefix because IMHO it's really helpful because the namespace is clearly visible **in any case**, and manually changing the name when cloning or forking is not necessary...

But yeah, let's see what @rnestler thinks :grin:

**Comment by rnestler** [comment]
I'm actually with @ubruhin on this one. I think a generic repository name like *converters* is not meaningful. *fontobene-converters* is much more descriptive.

> When cloning this repo into a non-namespaced directory, solving this issue is as simple as git clone https://github.com/fontobene/converters/ fontobene-converters.

This argument also works the other way around: When cloning this repo into a namespaced directory it's as simple as `git clone https://github.com/fontobene/fontobene-converters/ converters`. :wink:

**Comment by dbrgn** [comment]
Ok, feel free to rename :)

**Comment by ubruhin** [comment]
Done :)
